### ISSUE TITLE
[P1] remove `seealso` key from content

### ISSUE THREAD

**Issue by superyyrrzz** [ericholscher/sphinx-docfx-yaml#10]
Apart from #9 , The key `See also:` should be removed from content.

Now:
```
seealso: 'See also: [1]  J. Duchi...'
```

Expected:
```
seealsoContent: '[1]  J. Duchi...'
```

**Comment by hellosnow** [comment]
Should "Bases: `cntk.cntk_py.Value`" removed from summary, which has been added into inheritance tree?

Refer to [cntk.core.Value.yml](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L29)

**Comment by superyyrrzz** [comment]
@hellosnow Yes, add another issue to track it. #13

**Comment by ericholscher** [comment]
Closing this, tracking the changes in #13.
