### ISSUE TITLE
[P1]Syntax confusion

### ISSUE THREAD

**Issue by hellosnow** [ericholscher/sphinx-docfx-yaml#11]
For syntax of [cntk.core.Value](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L39), seems mismatch with source code [Argument of core.Value](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/core.py#L238)? The source code has 3 parameters while our yml has 6 parameters? Is it by design or something we misunderstood? Thanks @ericholscher

**Comment by ericholscher** [comment]
Guessing this is because I'm using an old version of the library, because CNTK can't be used with the local GitHub checkout, so I have to use the version installed on the docker image.

**Comment by superyyrrzz** [comment]
@ericholscher It should be the case in @hellosnow 's sample. I still found some syntax.content missing pameters, while it should have parameters from syntax.parameters in YAML, like [create()](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L85), [one_hot()](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L177)

Seems already mentioned in [this comment](https://github.com/ericholscher/sphinx-docfx-yaml/issues/4#issuecomment-299092669)

**Comment by bianliu1013** [comment]
PR: https://github.com/ericholscher/sphinx-docfx-yaml/pull/23
