### ISSUE TITLE
[P1] remove 'Bases: `...`' from summary

### ISSUE THREAD

**Issue by superyyrrzz** [ericholscher/sphinx-docfx-yaml#13]
Now the summary contains base class information like `` Bases: `...` `` at the start of summary. As YAML has another property `inheritance` for this purpose, this line can be removed. e.g.

Now:
```
 summary: 'Bases: `cntk.cntk_py.Value`

    Internal representation of minibatch data.'
```

Expected
```
 summary: 'Internal representation of minibatch data.'
```

**Comment by ericholscher** [comment]
Bases isn't defined anywhere that I can see: http://www.sphinx-doc.org/en/stable/ext/napoleon.html -- so there isn't a way for me to parse this out of the doctree, as stands.

**Comment by superyyrrzz** [comment]
I'm curious when this line `Bases: ...` is introduced, as it's doesn't appear in source code's original docstring. Is it Sphinx's default behavior to add this line? Or some plugin adds it? Is it configurable?
