### ISSUE TITLE
[P1] extract Examples to a seperate property

### ISSUE THREAD

**Issue by superyyrrzz** [ericholscher/sphinx-docfx-yaml#14]
Now the example is in summary without extra format, so it's hard to render it as Sphinx does. DocFX's YAML model has an `example` property for this purpose. Adding ` ``` ` at the start and the end of it can make it renders like Sphinx does. I think it should apply for both `Example` and `Examples` from [Napoleon's documentation](http://www.sphinx-doc.org/en/stable/ext/napoleon.html#docstring-sections). e.g.

Source:
```
    Some summary.

    Examples:
        >>> # Use a fixed momentum of 1100 for all samples
        >>> m = momentum_as_time_constant_schedule(1100)

        >>> # Use the time constant 1100 for the first 1000 samples,
        >>> # then 1500 for the remaining ones
        >>> m = momentum_as_time_constant_schedule([1100, 1500], 1000)
```

Now in YAML:
```yaml
  summary: 'Some summary.

    -[ Examples ]-

    >>> # Use a fixed momentum of 1100 for all samples

    >>> m = momentum_as_time_constant_schedule(1100)

    >>> # Use the time constant 1100 for the first 1000 samples,

    >>> # then 1500 for the remaining ones

    >>> m = momentum_as_time_constant_schedule([1100, 1500], 1000)'
```

Expected in YAML:
```yaml
  summary: 'Some summary.'
  example:
  - '```
    >>> # Use a fixed momentum of 1100 for all samples
    >>> m = momentum_as_time_constant_schedule(1100)
     ```'
  - '```
    >>> # Use the time constant 1100 for the first 1000 samples,
    >>> # then 1500 for the remaining ones
    >>> m = momentum_as_time_constant_schedule([1100, 1500], 1000)
     ```'
```

**Comment by ericholscher** [comment]
I looked into this, and there isn't really a clean way to export it, since it transform it into the following structure:

```
                    <rubric>
                        Examples
                    <doctest_block xml:space="preserve">
                        >>> # Use a fixed momentum of 1100 for all samples
                        >>> m = momentum_as_time_constant_schedule(1100)
                    <doctest_block xml:space="preserve">
                        >>> # Use the time constant 1100 for the first 1000 samples,
                        >>> # then 1500 for the remaining ones
                        >>> m = momentum_as_time_constant_schedule([1100, 1500], 1000)
```

I can't tell what is an example because it isn't nested in the doctree output. This is likely something that could be fixed in the napoleon extension.

**Comment by superyyrrzz** [comment]
Can we report a bug to Napoleon? I'm afraid it will block us if they can't fix it in time. After some reading about [doctree](http://docutils.sourceforge.net/docs/ref/doctree.html), I think `<rubric>` can be converted to markdown header, and `<doctest_block>` to markdown code, like:
````
    ### Examples
```
    >>> # Use a fixed momentum of 1100 for all samples
    >>> m = momentum_as_time_constant_schedule(1100)
```
```
    >>> # Use the time constant 1100 for the first 1000 samples,
    >>> # then 1500 for the remaining ones
    >>> m = momentum_as_time_constant_schedule([1100, 1500], 1000)'
```
`````

**Comment by ericholscher** [comment]
Looks like `napoleon_use_admonition_for_examples` might be the thing we need to use. It seems the examples section can be arbitrary RST, so the `napoleon_use_admonition_for_examples` config seems to allow nesting it, so we can extract it properly, and then transform it normally. This would be an additional bit to add `doctest_block` output to the writer as well.

**Comment by superyyrrzz** [comment]
Sounds nice 😄 Thanks Eric.

**Comment by ericholscher** [comment]
Believe this should be fixed.

**Comment by ericholscher** [comment]
It requires setting the above setting in order for it to work properly. I put a note about this in the docs.

**Comment by superyyrrzz** [comment]
Thanks Eric. I've seen the updated YAML and some questions:
1. Can the empty line between lines be removed? It doesn't exists in the original docstring. As the markdown code will preserve the empty line in the output HTML, it seems a bit strange.
2. I found the second example is lost. In our model example is an array, it can fit this.
3. Should move example out of syntax.

Now
```
syntax:
    content: momentum_as_time_constant_schedule()
    example: '````


      >>> # Use a fixed momentum of 1100 for all samples

      >>> m = momentum_as_time_constant_schedule(1100)

      ````'
```
Expected
```
syntax:
    content: momentum_as_time_constant_schedule()
example:
- '````
  >>> # Use a fixed momentum of 1100 for all samples
  >>> m = momentum_as_time_constant_schedule(1100)
  ````'
- '````
  >>> # Use the time constant 1100 for the first 1000 samples,
  >>> # then 1500 for the remaining ones
  >>> m = momentum_as_time_constant_schedule([1100, 1500], 1000)
  ````'
```

**Comment by ericholscher** [comment]
Pushed up a fix to the open PR, and added a test.

**Comment by superyyrrzz** [comment]
Thanks @ericholscher, the test looks good. BTW, can the example be moved out of syntax?

**Comment by bianliu1013** [comment]
PR: https://github.com/ericholscher/sphinx-docfx-yaml/pull/24

**Comment by superyyrrzz** [comment]
@herohua see this issue. From eric's xml sample, I think Sphinx take all the example as code block. But in [this](https://cntk.ai/pythondocs/cntk.core.html#cntk.core.Value.mask) case, it seems to be a rst text. I'll further investigate it.

**Comment by superyyrrzz** [comment]
As Eric mentioned above, example part allows arbitrary rst content. I think it can be converted to markdown by parsing the xml structure.

**Comment by bianliu1013** [comment]
add napoleon_use_admonition_for_examples = True to
https://github.com/MicrosoftDocs/cognitive-toolkit-docs-python/blob/master/ci_scripts/conf.py
