### ISSUE TITLE
[P1] Some other invalid cross reference

### ISSUE THREAD

**Issue by superyyrrzz** [ericholscher/sphinx-docfx-yaml#18]
Follow up #8. The original `` :class:`~cntk.core.Value` `` (see [here](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/core.py#L29)) is converted into `` `Value` ``(see [here](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.NDArrayView.yml#L31)), which is expected to be `@cntk.core.Value`. Compared with the correctly handled xref, this one seems to have `~` prefix.

I think this issue should also apply for syntax.parameters.type, the `DeviceDescriptor` [here](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.NDArrayView.yml#L54) should be `cntk.device.DeviceDescriptor`, generated from :class:`~cntk.device.DeviceDescriptor` ([source](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/core.py#L36)). Should they be fixed together?

**Comment by superyyrrzz** [comment]
Add a case: `` :class:`~cntk.core.Value` `` [here](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/internal/sanitize.py#L149) is converted to `[Value](cntk.core.html.md#cntk.core.Value.md)`. Expected is `@cntk.core.Value`.

**Comment by bianliu1013** [comment]
PR: https://github.com/ericholscher/sphinx-docfx-yaml/pull/26
