### ISSUE TITLE
[P2] use Python's type without mapping

### ISSUE THREAD

**Issue by superyyrrzz** [ericholscher/sphinx-docfx-yaml#21]
This is a design change. See the original design:  http://sphinx-docfx-yaml.readthedocs.io/en/latest/design.html#yaml-syntax

Seems no type mapping is needed now as we are using new uref’s model. We can use the type in Python directly.

now:
``` yml
- _type: attribute
- type: property
```

expected:
``` yml
- type: attribute
```

**Comment by bianliu1013** [comment]
fixed commit: 
https://github.com/ericholscher/sphinx-docfx-yaml/pull/17/commits/3b8cf44e1dd077970a3b8f102482874b1d81083b

**Comment by superyyrrzz** [comment]
As this is a breaking change for template, @bianliu1013 please create a PR when updating YAML files. When template change is ready, @adkinn can merge the PR to master.
