### ISSUE TITLE
[P1]Add syntax/content in yaml

### ISSUE THREAD

**Issue by hellosnow** [ericholscher/sphinx-docfx-yaml#4]
Syntax/content should be added to [cntk.debugging.debug.yml](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.debugging.debug.yml#L88) as following, to be rendered as the syntax section in final templates.

Example:
```yaml
syntax:
    content: debug_model(model, in_stream=sys.stdin, out_stream=sys.stdout, exit_func=sys.exit)
```

**Comment by ericholscher** [comment]
Believe this should be fixed in the latest version:

```
  syntax:
    content: NDArrayView(self, shape, data_type, device=None)
```

**Comment by hellosnow** [comment]
@ericholscher the syntax in [on_hot](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L189) should be `static one_hot(batch, num_classes, dtype=None, device=None)` following [CNTK readTheDocs document](https://www.cntk.ai/pythondocs/cntk.core.html#cntk.core.Value.one_hot)?

**Comment by superyyrrzz** [comment]
@hellosnow track in #11 . Can we close this issue?
