### ISSUE TITLE
[P1]Invalid cross references

### ISSUE THREAD

**Issue by hellosnow** [ericholscher/sphinx-docfx-yaml#8]
We found invalid cross references in several places:
1. `@one_hot` should be `@cntk.core.Value.one_hot` in [cntk.core.Value.yml](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L51)
2. `@NDArrayView` in [cntk.core.Value.yml](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L126) should be `@cntk.core.NDArrayView` in [cntk.core.NDArrayView.yml](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.NDArrayView.yml#L54)
3. `@Value` should be `@cntk.core.Value` in [cntk.core.Value.yml](https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L205)

@ericholscher are these above issues in the same pattern? Could we figure out why some cross reference are valid while some are not?

**Comment by ericholscher** [comment]
Sphinx supports the concept of relative reference, so those are defined as such in the original Sphinx scripts. I can see if I can resolve the "full" reference at that point.

**Comment by ericholscher** [comment]
I've fixed this, and the writer is now outputting `[from_dense()](xref:cntk.core.NDArrayView.from_dense)` -- I'm guessing this isn't what y'all want, but prefer the `@` syntax?

**Comment by ericholscher** [comment]
Updated to do the `@` syntax for now, let me know if you'd prefer otherwise.

**Comment by hellosnow** [comment]
@ericholscher we found in https://github.com/bradygaster/python-sdk-dev/blob/cntk-yaml/python-sdk-dev/docfx_yaml/cntk.core.Value.yml#L29, `cntk.cntk_py.Value` in “Bases: `cntk.cntk_py.Value`“ is not transformed to @ syntax, should it be fixed? BTW, `bases` should be removed from summary since inheritance has present the relationship?

**Comment by superyyrrzz** [comment]
@ericholscher `@` syntax can handle most cases. Agree to use it for now. As Sphinx supports explicit title and `~` prefix in cross reference([doc](http://www.sphinx-doc.org/en/stable/markup/inline.html#xref-syntax)), actually it should be converted into different forms of xref in DocFX. I think this can be an improvement later.

BTW, I found the cross reference is converted correctly in summary's rst. e.g.
* Source: `` ... :meth:`~cntk.ops.output_variable`.``
* Now: `... [output_variable()](cntk.ops.html.md#cntk.ops.output_variable.md)`
* Expected: `... @cntk.ops.output_variable`

**Comment by superyyrrzz** [comment]
add #18 to follow the remaining issue in cross reference. @hellosnow can you help close this one?

**Comment by hellosnow** [comment]
Closing now
